### ISSUE TITLE
MotionModel Clean-up

### ISSUE THREAD

**Issue by punov** [Hivemapper/odc-api#124]
We're revisited with Evan the code of the motion model,
proposed approach is here: 
https://gist.github.com/evanmoss/2a1a2f8d7de85fef5796e7b4371a3e6a

Solution is going to be cleaned up according to approach proposed.

**Comment by jayalberts** [comment]
let us know about testing requirements

**Comment by jayalberts** [comment]
discovering defects, fixing, drive testing this afternoon.

**Comment by jayalberts** [comment]
issues with continuous framekm: 10s period of sensor info missing related to SQLite migration / data logger.

need to pre filter data before inserting into table to mitigate problem, currently in testing.

**Comment by jayalberts** [comment]
still having unexpected symbols in ublox. fixed side effects but not root cause.

**Comment by punov** [comment]
Solution is ready to be wrapped for this round of testing:
i will share the latest code with Evan once cleaned up.

Unexpected UBLOX symbols will be addressed with the next iteration

**Comment by jayalberts** [comment]
checking out logs
main problem is camera trying to pack recent framekm but it fails because no images are ready, no proper handling to move on so it gets stuck trying to pack same framekm over and over. 
Fix is straight forward.

S is doing better on continuous numbers. HDC chunking more often because less frames to select from, especially if FPS or GPS drops.
